-- MediKart authentication database schema.
-- Registration inserts into users; login reads from the same users table.

CREATE DATABASE IF NOT EXISTS medikart
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE medikart;

-- ==============================
-- REGISTRATION / LOGIN USERS
-- ==============================
CREATE TABLE IF NOT EXISTS users (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(255) NOT NULL,
  phone VARCHAR(20) NULL,
  hashed_password VARCHAR(255) NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  is_verified BOOLEAN NOT NULL DEFAULT FALSE,
  is_admin BOOLEAN NOT NULL DEFAULT FALSE,
  otp VARCHAR(6) NULL,
  otp_expires_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_users_email (email),
  KEY ix_users_email (email),
  KEY ix_users_is_active (is_active)
) ENGINE=InnoDB;

-- ==============================
-- REGISTRATION EXAMPLE
-- ==============================
-- Passwords must be bcrypt hashes generated by the backend.
-- INSERT INTO users (name, email, phone, hashed_password)
-- VALUES ('Example User', 'user@example.com', NULL, '<bcrypt-hash>');

-- ==============================
-- LOGIN LOOKUP EXAMPLE
-- ==============================
-- The backend verifies the submitted password against hashed_password.
-- SELECT id, name, email, phone, hashed_password, is_active, is_admin
-- FROM users
-- WHERE email = 'user@example.com'
-- LIMIT 1;

-- ==============================
-- SAFE USER DATA VIEW
-- ==============================
-- Never expose hashed_password, otp, or otp_expires_at to the frontend.
CREATE OR REPLACE VIEW user_account_data AS
SELECT
  id,
  name,
  email,
  phone,
  is_active,
  is_verified,
  is_admin,
  created_at
FROM users;
